# Generated by Django 2.2.4 on 2019-10-12 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=30)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Player', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
