# Generated by Django 2.2.4 on 2019-10-12 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_paymenthistory_mid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='TXNID',
            field=models.CharField(max_length=64),
        ),
    ]
