# Generated by Django 2.2.4 on 2019-10-14 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_auto_20191012_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='REFUNDAMT',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='TXNTYPE',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='RESPCODE',
            field=models.CharField(max_length=10),
        ),
    ]
