# Generated by Django 2.2.4 on 2019-10-11 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20191011_1506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='first_solve',
            new_name='is_level_solved',
        ),
    ]
