# Generated by Django 2.2.4 on 2019-10-11 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='badge',
            old_name='one_player_only',
            new_name='one_time_only',
        ),
        migrations.AddField(
            model_name='badgetoplayer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
