# Generated by Django 2.2.4 on 2019-10-13 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0004_auto_20191013_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='icon',
        ),
    ]
